### ISSUE TITLE
Avoid a duplicate word in README.md

### ISSUE THREAD

**Issue by elfring** [thierry-martinez/pyast#4]
I suggest to [avoid an undesirable word repetition](https://github.com/thierry-martinez/pyast/blob/3544e0089bab9d4aefa21da40187827fdd594d69/README.md#usage "Update candidate").

```diff
-(The module corresponding the the version of the Python interpreter
+(The module corresponding to the Python interpreter version
```

**Comment by thierry-martinez** [comment]
Fixed. Thanks!
