### ISSUE TITLE
[opam] dependency to merlin is too strict

### ISSUE THREAD

**Issue by vsiles** [thierry-martinez/pyast#8]
Hi !
On a recent opam checkout, pyast.0.1.1 shows the following dependency:
```
"menhir" {>= "20210419" & < "20211215"}
```

However the github version doesn't have the upper bound. We're starting a project that requires a 2022 version of menhir, so we were wondering if you could do a new release to bump the dependency restrictions and enable more recent menhir versions to work with pyast ?

Best,
Vincent

**Comment by thierry-martinez** [comment]
Thank you for your interest in `pyast` and sorry for the delay! I am not sure why this upper-bound has been introduced (it does not seem to be needed for `pyast` to compile; I think it was part of a bigger change in opam repository to fix some incompatibilities introduced by newer menhir versions). I just published a new release of pyast in opam (https://github.com/ocaml/opam-repository/pull/22339), introducing compatibility with Python 3.11, and removed the menhir version upper-bound for previous releases.

**Comment by thierry-martinez** [comment]
Fixed with https://github.com/ocaml/opam-repository/pull/22339 .
